#:import FadeTransition kivy.uix.screenmanager.FadeTransition
<MainWindow>:
    id: win_main
    
    ScreenManager:
        id: scrn_mnger
        transition: FadeTransition()

        Screen:
            id: scrn_login
            name: 'scrn_login'

        Screen:
            id: scrn_tela
            name: 'scrn_tela'

        Screen:
            id: scrn_telacadastro
            name: 'scrn_telacadastro'